# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-17 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='positive',
            field=models.BooleanField(default=True),
        ),
    ]
