# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-17 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entry_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(default='income', max_length=140),
        ),
    ]
